version: '3.8'
services:
  frontend:
    platform: linux/arm64
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
      platforms:
        - linux/arm64
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

  backend:
    platform: linux/arm64
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
      platforms:
        - linux/arm64
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  database:
    image: postgres:13
    environment:
      POSTGRES_DB: renewable_energy
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: